### ISSUE TITLE
deepsec_api process should be detached from deepsec_ui

### ISSUE THREAD

**Issue by Opsse** [DeepSec-prover/deepsec_ui#15]
Seems to work in linux but maybe not with mac

**Comment by VincentCheval** [comment]
confirmed

**Comment by Opsse** [comment]
see: https://stackoverflow.com/questions/59646654/detach-a-process-after-the-started

**Comment by Opsse** [comment]
Fixed by 9908b4c

**Comment by Opsse** [comment]
For some reason it does't works with `scytl`

**Comment by VincentCheval** [comment]
Which scytl ? Can you send me the associated batch folder and file from 'result_files' ?

**Comment by Opsse** [comment]
[jzbrex_75a8.zip](https://github.com/DeepSec-prover/deepsec_ui/files/4065619/jzbrex_75a8.zip)

**Comment by VincentCheval** [comment]
Let's hope this is the last time we open/close it.
