### ISSUE TITLE
Undefined parameters

### ISSUE THREAD

**Issue by VincentCheval** [DeepSec-prover/deepsec_ui#26]
I get the following two error messages when I open a batch result that ended with an internal error.

```
console.js?a929:72 12:53:54.212 › Can't find the id "semantics.undefined" in the helpers file
```

and

```
console.js?a929:72 12:53:54.234 › Can't find the id "runOptions.distributed.undefined" in the helpers file
```

Since it's an internal error file, Deepsec did not reach the time where it computes these informations and so they may not appear in the json.

**Comment by Opsse** [comment]
Can't reproduce
