### ISSUE TITLE
Increasing the minimal length of frames in attack and equivalence simulator

### ISSUE THREAD

**Issue by VincentCheval** [DeepSec-prover/deepsec_ui#37]
We should increasing the minimal size of the frame so that the double column view is deactivated for the sequential view.

![image](https://user-images.githubusercontent.com/6087949/71922813-f93d9800-318b-11ea-80a5-5f36ff81fec8.png)

**Comment by Opsse** [comment]
`lg` breakpoint is too small but `xl` is too big
