### ISSUE TITLE
Bundle the application fonts

### ISSUE THREAD

**Issue by Opsse** [DeepSec-prover/deepsec_ui#55]
We need to find a way to bundle the application fonts to be sure that everybody have the save UI.

Probably need to use [@font-face](https://developer.mozilla.org/fr/docs/Web/CSS/@font-face) but I don't know how to make the font available in the bundled files.

For mono download _monaco_

**Comment by VincentCheval** [comment]
Haven't we solve that already ? I'm confused. I thought we put the "Helvetica-local" too.

**Comment by Opsse** [comment]
I think it's solved I just wanted your confirmation
