### ISSUE TITLE
Problems with DeepSec API Path

### ISSUE THREAD

**Issue by steve-kremer** [DeepSec-prover/deepsec_ui#60]
I encountered a few problems with the DeepSec API Path configuration:

 - I have a symbolic link to the DeepSec API executable; the symbolic link is found automatically but an error is given
 - when manually configuring the path (Settings)
a path of the form "\~/my local path to/deepsec_api" is not accepted (the '\~' is the problem);
giving the path, but not the filename, e.g. "/absolute/path/to/" is not accepted.

**Comment by VincentCheval** [comment]
Fix in b6afe9a for first bullet. Second bullet will not be fixed, i.e. we only accept absolute path. Though in b6afe9a, we have made it clearer + gave the option to select your executable.
