### ISSUE TITLE
When packaged in AppImage, doesn't detect the PATH correctly

### ISSUE THREAD

**Issue by VincentCheval** [DeepSec-prover/deepsec_ui#65]
Comments from the alpha testing:

On NixOS, trying to install the UI from the source using 'npm run electron:serve' or 'npm run electron:build' does not seem to work (apparently, 'electron:serve' starts a HTTP server accessible local via 8080). Further details on these should come soon.

Moreover, when using the package 'appimage', it does not find 'deepsec_api' even if it is in the path. Could it be a problem with 'which' or a similar issue we had on Mac OS ?

**Comment by Opsse** [comment]
Probably more related to AppImage than NixOS

**Comment by VincentCheval** [comment]
Fix in 5587b9bd0013ca96b60f5d891a865495fd1edf29
